name: ci

on:
  pull_request:
    branches:
      - main
      - production
  push:
    branches:
      - main
      - production
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Lint
        run: mvn spotless:check
      - name: Compile
        run: mvn compile
      - name: Test
        run: mvn test
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
