on:
  pull_request:
    branches:
      - main
      - production
  push:
    branches:
      - main
      - production
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distributions: 'corretto'
          cache: maven
      - name: Lint
        run: mvn spotless:check
      - name: Compile
        run: mvn compile
      - name: Test
        run: mvn test
